# -*- coding: utf-8 -*-
"""Alura ImersaoIA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1745EAVb-ZsUGnbcIKXU7Gfj77rJIMu6Z

# Nova seção
"""

!pip install google-genai

import os
from google.colab import userdata

os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')

from google import genai

client = genai.Client()

for model in client.models.list():
  print(model.name)

model = "gemini-2.0-flash"

resposta = client.models.generate_content(model=model,
                                         contents="Quem é a empresa por tras dos modelos Gemini?")

resposta

resposta.text

chat = client.chats.create(model=model)

resposta = chat.send_message("Oi, tudo bem?")
resposta.text

resposta = chat.send_message("Voce é um assistente pessoal, e você sempre responde de forma sucinta. Oque é Inteligencia Artificial?")
resposta.text

from google.genai import types

chat_config = types.GenerateContentConfig(
    system_instruction = "Voce é um assistente pessoal, e você sempre responde de forma sucinta. Oque é Inteligencia Artificial?",
)
chat = client.chats.create(model=model, config=chat_config)

resposta = chat.send_message("Qual é a capital do Paraná?")
resposta.text

chat.get_history()

prompt = input("Esperando Prompt: ")

while prompt != "fim":
  resposta = chat.send_message(prompt)
  print("Resposta: ", resposta.text)
  print("\n\n")
  prompt = input("Esperando Prompt: ")

chat.get_history()

chat_config2 = types.GenerateContentConfig(
    system_instruction = "Voce é um assistente pessoal, e você sempre responde de forma muito sarcastica",
)
chat2 = client.chats.create(model=model, config=chat_config2)

resposta = chat2.send_message("Qual é o personagem brasileiro de Overwatch?")

resposta.text

prompt = input("Esperando Prompt: ")

while prompt != "fim":
  resposta = chat2.send_message(prompt)
  print("Resposta: ", resposta.text)
  print("\n\n")
  prompt = input("Esperando Prompt: ")